import { portraitDataUri } from "./ids";
import type { OpsState } from "./types";

const now = Date.now();
const minutes = (n: number) => now - n * 60_000;
const seconds = (n: number) => now - n * 1000;

const soriya = portraitDataUri("Soriya Chan");
const rithy = portraitDataUri("Rithy K");
const dara = portraitDataUri("Dara Vann");

export const seedState: OpsState = {
  venue: "Aeon Mall Phnom Penh",
  scanning: false,
  toast: null,
  ticketSeq: 1003,
  alertSeq: 2045,
  detectionSeq: 94,
  cameras: [
    { id: "cam-01", name: "CAM-01", zone: "Info desk", rtspLabel: "rtsp://cam-01", protocol: "rtsp" },
    { id: "cam-03", name: "CAM-03", zone: "Food court", rtspLabel: "rtsp://cam-03", protocol: "rtsp" },
    { id: "cam-07", name: "CAM-07", zone: "Produce aisle", rtspLabel: "rtsp://cam-07", protocol: "rtsp" },
    { id: "cam-12", name: "CAM-12", zone: "Level 2 escalator", rtspLabel: "rtsp://cam-12", protocol: "rtsp" },
    { id: "cam-18", name: "CAM-18", zone: "Parking B", rtspLabel: "rtsp://cam-18", protocol: "rtsp" },
    { id: "cam-24", name: "CAM-24", zone: "Backroom", rtspLabel: "rtsp://cam-24", protocol: "rtsp" },
  ],
  rules: {
    roiEnabled: true,
    timeWindow: "all",
    cooldownSec: 60,
    objectTypes: ["human"],
  },
  cases: [
    {
      id: "case-soriya",
      ticketId: "TKT-1001",
      kind: "missing",
      status: "match_pending",
      photo: soriya,
      createdAt: minutes(18),
      source: "web",
      missing: {
        name: "Soriya Chan",
        age: "6",
        clothing: "Yellow dress, red backpack",
        lastSeenZone: "Food court",
        reporterName: "Malis Chan",
        reporterPhone: "+855 12 440 118",
        ephemeral: true,
      },
    },
    {
      id: "case-rithy",
      ticketId: "TKT-1002",
      kind: "watchlist",
      status: "in_progress",
      photo: rithy,
      createdAt: minutes(42),
      source: "web",
      watchlist: {
        alias: "Rithy K.",
        category: "shoplifter",
        notes: "Produce theft, Lucky Super exchange.",
        shareAcrossVenues: true,
      },
    },
    {
      id: "case-dara",
      ticketId: "TKT-1003",
      kind: "missing",
      status: "expired",
      photo: dara,
      createdAt: minutes(96),
      expiredAt: minutes(40),
      source: "telegram",
      missing: {
        name: "Dara Vann",
        age: "8",
        clothing: "Blue school shirt",
        lastSeenZone: "Level 2",
        reporterName: "Sreypov Vann",
        reporterPhone: "+855 77 201 334",
        ephemeral: true,
      },
    },
  ],
  detections: [
    {
      id: "DET-0091",
      cameraId: "cam-12",
      objectClass: "human",
      confidence: 0.91,
      bbox: { x: 38, y: 22, w: 28, h: 58 },
      ts: minutes(3),
      roiHit: true,
      afterHours: false,
      caseId: "case-soriya",
    },
    {
      id: "DET-0092",
      cameraId: "cam-03",
      objectClass: "human",
      confidence: 0.74,
      bbox: { x: 18, y: 30, w: 22, h: 52 },
      ts: seconds(22),
      roiHit: true,
      afterHours: false,
    },
    {
      id: "DET-0093",
      cameraId: "cam-18",
      objectClass: "vehicle",
      confidence: 0.88,
      bbox: { x: 12, y: 40, w: 60, h: 38 },
      ts: seconds(8),
      roiHit: false,
      afterHours: false,
    },
    {
      id: "DET-0094",
      cameraId: "cam-24",
      objectClass: "human",
      confidence: 0.69,
      bbox: { x: 44, y: 18, w: 24, h: 62 },
      ts: seconds(41),
      roiHit: true,
      afterHours: true,
    },
  ],
  alerts: [
    {
      id: "ALT-2044",
      detectionId: "DET-0091",
      cameraId: "cam-12",
      caseId: "case-soriya",
      reason: "Possible match — Safety Wedge. Human verification required.",
      ts: minutes(3),
      mediaKind: "still",
      confidence: 0.91,
      telegramState: "sent",
      operatorAction: null,
      dismissed: false,
    },
    {
      id: "ALT-2045",
      detectionId: "DET-0094",
      cameraId: "cam-24",
      reason: "Restricted backroom — human in ROI.",
      ts: minutes(11),
      mediaKind: "gif",
      confidence: 0.69,
      telegramState: "sent",
      operatorAction: "verify",
      dismissed: false,
    },
  ],
  messages: [
    {
      id: "msg-01",
      direction: "out",
      method: "getMe",
      body: "@inbound_ops_bot connected · Aeon Mall Phnom Penh",
      ts: minutes(50),
    },
    {
      id: "msg-02",
      direction: "in",
      method: "ticket",
      body: "Dara Vann, age 8, blue school shirt, last seen Level 2.",
      ts: minutes(96),
      ticketId: "TKT-1003",
    },
    {
      id: "msg-03",
      direction: "out",
      method: "ticket",
      body: "Ticket opened. Ephemeral search started on 6 cameras.",
      ts: minutes(96),
      ticketId: "TKT-1003",
      json: JSON.stringify(
        { status: "success", data: { ticket_id: "TKT-1003", status: "In Progress" } },
        null,
        2,
      ),
    },
    {
      id: "msg-04",
      direction: "out",
      method: "sendMessage",
      body: "ALERT CAM-12 · Level 2 escalator\nSafety Wedge · pending verification\nSoriya Chan · confidence 0.91",
      ts: minutes(3),
      alertId: "ALT-2044",
      ticketId: "TKT-1001",
    },
  ],
};
